### ISSUE TITLE
README.md can have more information about usage

### ISSUE THREAD

**Issue by TachyonFlare** [am3o/tasmota_exporter#4]
This project looks really cool and I wanted to use this for monitoring power usage on my tasmota plugs. 

However, it is unclear from the docs on the format of `CONFIG_FILE` or how to use the environment variables to enable monitoring multiple tasmota devices. I am open to doing that work of figuring it out but reaching out here first to see if that part of the roadmap.

**Comment by am3o** [comment]
I hope, I'm not to late for you. It's my fault, I'm forgetting to write a documentation for the project and I should do that for sure.

Just an example configuration looks like:
```haskell 
devices:
  - IP: "10.0.0.230"
    Name: "office-workplace"
    Type: "gosund"
  - IP: ...
    Name: ...
    Type: ...
  ```
 
 I didn't test the application for multiple devices. 
 
 If you need some more help, feel free to contact me.

**Comment by TachyonFlare** [comment]
No problem, thanks for confirmation. I was able to dig this info through the information in the repo. Might raise a PR with changes to readme If I can find some time.
